repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

  - name: prometheus
    url: https://prometheus-community.github.io/helm-charts

  - name: faro-collector
    url: https://leozw.github.io/faro-collector

  - name: jetstack
    url: https://charts.jetstack.io

hooks:
  - events: ["prepare"]
    showlogs: true
    command: "./helmfile-global-hooks.sh"
    args:
      - "{{ .HelmfileCommand }}"
      - "prepare"
  - events: ["cleanup"]
    showlogs: true
    command: "./helmfile-global-hooks.sh"
    args:
      - "{{ .HelmfileCommand }}"
      - "cleanup"

releases:
  ######## Certificate #########
  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    values:
      - ./cert-manager/values.yaml
    hooks:
      - events: ["postsync"]
        command: "kubectl"
        args:
          - "wait"
          - "--for=condition=Available"
          - "deployment/cert-manager"
          - "-n"
          - "cert-manager"
          - "--timeout=180s"
      - events: ["postsync"]
        command: "kubectl"
        args:
          - "wait"
          - "--for=condition=Available"
          - "deployment/cert-manager-webhook"
          - "-n"
          - "cert-manager"
          - "--timeout=180s"
      - events: ["postsync"]
        command: "kubectl"
        args:
          - "wait"
          - "--for=condition=Available"
          - "deployment/cert-manager-cainjector"
          - "-n"
          - "cert-manager"
          - "--timeout=180s"

  ######## prometheus #########
  - name: elven
    namespace: monitoring
    createNamespace: true
    chart: prometheus/kube-prometheus-stack
    values:
      - ./prometheus/values-prometheus.rendered.yaml

  ######## alloy logs #########
  - name: elven-logs-collector
    namespace: monitoring
    createNamespace: true
    chart: grafana/alloy
    values:
      - ./alloy/values-alloy.yaml

  - name: elven-collector-fe
    namespace: monitoring
    createNamespace: true
    chart: faro-collector/faro-collector
    values:
      - ./collector-fe/values.yaml

  - name: beyla
    namespace: monitoring
    createNamespace: true
    installed: false
    chart: grafana/beyla
    values:
      - ./beyla/values.yaml
