repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

  - name: prometheus
    url: https://prometheus-community.github.io/helm-charts

  - name: faro-collector
    url: https://leozw.github.io/faro-collector

  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    values:
      - ./cert-manager/values.yaml

  - name: prometheus
    namespace: monitoring
    createNamespace: true
    chart: prometheus/kube-prometheus-stack
    values:
      - ./prometheus/values-prometheus.yaml

  - name: promtail
    namespace: monitoring
    createNamespace: true
    chart: grafana/promtail
    values:
      - ./promtail/values-promtail.yaml

  - name: collector-fe
    namespace: default
    createNamespace: true
    chart: faro-collector/faro-collector
    values:
      - ./collector-fe/values.yaml
    needs:
      - cert-manager/cert-manager
hooks:
  - events: ["prepare"]
    command: "kubectl"
    args: ["apply", "-k", "."]
