apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: instrumentation
  namespace: default
spec:
  exporter:
    endpoint: "http://opentelemetrycollector.monitoring.svc.cluster.local:4318"
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "1"

  go:
    image: "grafana/beyla:latest"
    env:
      - name: BEYLA_METRICS_ENABLED
        value: "true"
      - name: OTEL_METRICS_EXPORTER
        value: "otlp"
      - name: BEYLA_OPEN_PORT
        value: "8080"
      - name: BEYLA_BPF_TRACK_REQUEST_HEADERS
        value: "true"
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://opentelemetrycollector.monitoring.svc.cluster.local:4318"

    resourceRequirements:
      limits:
        cpu: "500m"
        memory: "1Gi"
      requests:
        cpu: "250m"
        memory: "512Mi"
  nodejs:
    env:
      - name: OTEL_NODE_RESOURCE_DETECTORS
        value: all
      - name: OTEL_TRACES_EXPORTER
        value: "otlp"
      - name: OTEL_METRICS_EXPORTER
        value: "otlp"
      - name: OTEL_NODE_ENABLED_INSTRUMENTATIONS
        value: "all"
      - name: OTEL_NODE_RESOURCE_DETECTORS
        value: "all"
      - name: OTEL_NODE_DISABLED_INSTRUMENTATIONS
        value: "fs"
      - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
        value: "http://opentelemetrycollector.monitoring.svc.cluster.local:4318/v1/traces"
      - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
        value: "http://opentelemetrycollector.monitoring.svc.cluster.local:4318/v1/metrics"
  java:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://opentelemetrycollector.monitoring.svc.cluster.local:4317
      - name: OTEL_TRACES_EXPORTER
        value: "otlp"
      - name: OTEL_METRICS_EXPORTER
        value: "otlp"
  dotnet:
    env:
      - name: OTEL_DOTNET_AUTO_METRICS_CONSOLE_EXPORTER_ENABLED
        value: "false"
      - name: OTEL_DOTNET_AUTO_TRACES_CONSOLE_EXPORTER_ENABLED
        value: "false"
      - name: OTEL_DOTNET_AUTO_LOGS_CONSOLE_EXPORTER_ENABLED
        value: "false"
      - name: OTEL_TRACES_EXPORTER
        value: "true"
      - name: OTEL_METRICS_EXPORTER
        value: "true"
      - name: OTEL_LOGS_EXPORTER
        value: "true"

---
# Se precisar colocar em mais de um Namespace, basta duplicar a config separadas por três dashs "---"

# apiVersion: opentelemetry.io/v1alpha1
# kind: Instrumentation
# metadata:
#   name: instrumentation
#   namespace: monitoring
# spec:
#   exporter:
#     endpoint: "http://opentelemetrycollector.monitoring.svc.cluster.local:4318"
#   propagators:
#     - tracecontext
#     - baggage
#     - b3
#   sampler:
#     type: parentbased_traceidratio
#     argument: "1"

#   go:
#     env:
#       - name: OTEL_EXPORTER_OTLP_ENDPOINT
#         value: http://opentelemetrycollector.monitoring.svc.cluster.local:4318
#   nodejs:
#     env:
#       - name: OTEL_NODE_DISABLED_INSTRUMENTATIONS
#         value: fs
#       - name: OTEL_NODE_RESOURCE_DETECTORS
#         value: all
#   java:
#     env:
#       - name: OTEL_EXPORTER_OTLP_ENDPOINT
#         value: http://opentelemetrycollector.monitoring.svc.cluster.local:4317
#   dotnet:
#     env:
#       - name: OTEL_DOTNET_AUTO_METRICS_CONSOLE_EXPORTER_ENABLED
#         value: "false"
#       - name: OTEL_DOTNET_AUTO_TRACES_CONSOLE_EXPORTER_ENABLED
#         value: "false"
#       - name: OTEL_DOTNET_AUTO_LOGS_CONSOLE_EXPORTER_ENABLED
#         value: "false"
#       - name: OTEL_TRACES_EXPORTER
#         value: "true"
#       - name: OTEL_METRICS_EXPORTER
#         value: "true"
#       - name: OTEL_LOGS_EXPORTER
#         value: "true"
