apiVersion: v1
kind: Secret
metadata:
  name: elven-collector-fe-env-secret
  namespace: monitoring
type: Opaque
stringData:
  SECRET_KEY: bGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9asdyJpc3MiOiJlbHZlbi1sZ3RtLWp3dCIsIm9yZ0
  LOKI_URL: https://loki.elvenobservability.com
  ALLOW_ORIGINS: https://*.elvenobservability.com
  JWT_ISSUER: elven-observability
