apiVersion: v1
kind: Secret
metadata:
  name: collector-fe-env-secret
  namespace: default
type: Opaque
stringData:
  SECRET_KEY: 
  LOKI_URL: https://loki.elvenobservability.com/loki/api/v1/push
  LOKI_API_TOKEN: 
  ALLOW_ORIGINS: 
  JWT_ISSUER: 